[workspace]
authors = ["Soumya Das <soumyadasjr@gmail.com>"]
channels = ["conda-forge"]
name = "Chess_MinMax"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
start = "npx serve"

[dependencies]
nodejs = ">=25.8.2,<25.9"
